import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import SessionProvider from "@/components/Auth/SessionProvider";
import { cn } from "../../lib/utils";
import Navigation from "@/components/Dashboard/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     
        <body className={cn(inter.className, "")}>
        <SessionProvider>
          <div className="flex lg:h-screen bg-amber-200">
          <Navigation />
          <main className=" bg-red-700 w-full">{children}</main>
          </div>

          </SessionProvider>
        </body>
      
    </html>
  );
}
