import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import SessionProvider from "@/components/Auth/SessionProvider";
import { cn } from "../../lib/utils";
import Navigation from "@/components/Dashboard/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "bg-gray-50")}>
        <div className="flex lg:h-screen p-2">
          <Navigation />
          <main className="w-full p-4">{children}</main>
        </div>
      </body>
    </html>
  );
}
